# Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.

"""Scalable, topology-aware training diagnostic primitives."""

from .accumulator import (
    DerivedStatistic,
    PackedSlots,
    PackedSufficientStatistics,
    ProcessGroupIdentity,
    ReductionBinding,
    ReductionKind,
)
from .capture import (
    CaptureTopology,
    LayerCaptureTarget,
    StagedTokenMask,
    Tier0CaptureResult,
    Tier0CaptureSession,
    TokenLayout,
    discover_layer_capture_targets,
    pack_valid_token_mask_sideband,
    slice_sequence_parallel_mask,
    stage_valid_token_mask,
    unpack_valid_token_mask_sideband,
)
from .normalization import CanonicalDgradNormalizer
from .registry import (
    DenominatorKind,
    MaskKind,
    MetricDescriptor,
    MetricFamily,
    MetricNormalizationAdapter,
    MetricRegistry,
    NormalizationKind,
    Ownership,
    PartitionAxis,
    ReplicationAxis,
    StatisticKind,
)
from .schema import (
    SCHEMA_PREFIX,
    SCHEMA_VERSION,
    TIER0_KEYS,
    TIER0_METADATA_KEYS,
    TIER0_METRIC_KEYS,
    TIER0_PREFIX,
    Tier0Reason,
    Tier0Status,
    assert_payload_schema,
)

__all__ = [
    "CanonicalDgradNormalizer",
    "CaptureTopology",
    "DerivedStatistic",
    "DenominatorKind",
    "LayerCaptureTarget",
    "MaskKind",
    "MetricDescriptor",
    "MetricFamily",
    "MetricNormalizationAdapter",
    "MetricRegistry",
    "NormalizationKind",
    "Ownership",
    "PackedSlots",
    "PackedSufficientStatistics",
    "PartitionAxis",
    "ProcessGroupIdentity",
    "ReductionBinding",
    "ReductionKind",
    "ReplicationAxis",
    "SCHEMA_PREFIX",
    "SCHEMA_VERSION",
    "StagedTokenMask",
    "StatisticKind",
    "TIER0_KEYS",
    "TIER0_METADATA_KEYS",
    "TIER0_METRIC_KEYS",
    "TIER0_PREFIX",
    "Tier0Reason",
    "Tier0CaptureResult",
    "Tier0CaptureSession",
    "Tier0Status",
    "TokenLayout",
    "assert_payload_schema",
    "discover_layer_capture_targets",
    "pack_valid_token_mask_sideband",
    "slice_sequence_parallel_mask",
    "stage_valid_token_mask",
    "unpack_valid_token_mask_sideband",
]
